### ISSUE TITLE
Any code coming here ? 

### ISSUE THREAD

**Issue by Tazer** [aspnet/SignalR-Client-Java#1]
Hello,

Is there any plans to add code here ? Cause I'm interested in a project aspnet 5 with signalr , working with android client (java)

**Comment by Eilon** [comment]
The Java client (for Android) is still in its original repo here: https://github.com/SignalR/java-client

**Comment by Tazer** [comment]
@Eilon Yeah I have seen that repo, but seems it's not accpeting pull request and issue not responded on. So was hoping that something new or at least the old code was moved. So maybe it could spark some activity. But thanks for the comment

**Comment by Eilon** [comment]
@damianedwards @davidfowl on this. We need to figure out the relative priorities of these.

**Comment by ol-loginov** [comment]
Any update?

**Comment by Eilon** [comment]
Ping @DamianEdwards / @davidfowl again.

I don't think anything has changed here, the previous Java client is still all there is.
